### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by 5chdn**

### CODE REVIEW

**Comment by NikVolf** [comment]
Again, would be GPL a good choice for code that is supposed to be copy-pasted into other people new projects?

**Comment by lexfrl** [comment]
let's merge it. We could change it later if we want

**Comment by 5chdn** [comment]
I'm not overly political here. Happy to change it to whatever you want most.

I also agree now that example code should be less restrictive licensed.

**Comment by 5chdn** [comment]
#29

**Pull request closed without merging**
